fix(ini): a stray quote was causing INI parsing to break
Error: parsing template grafana.ini.tpl (template: grafana.ini.tpl:208: bad character U+0022 '"')